version: "3"
services:
  trade_bot:
    build: .
    volumes:
      - ./.git:/app/.git:ro
      - ./scripts:/app/scripts:ro
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./tmp:/tmp/alphasea-trade-bot
    working_dir: /app
    environment:
      CCXT_EXCHANGE: ${CCXT_EXCHANGE:-ftx}
      CCXT_API_KEY: ${CCXT_API_KEY}
      CCXT_API_SECRET: ${CCXT_API_SECRET}
      CCXT_SUBACCOUNT: ${CCXT_SUBACCOUNT}
      ALPHASEA_AGENT_BASE_URL: ${ALPHASEA_AGENT_BASE_URL:-http://host.docker.internal:8070}
      ALPHASEA_LEVERAGE: ${ALPHASEA_LEVERAGE:-1.0}
      ALPHASEA_LOG_LEVEL: debug
    command: python -m src.main
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
    extra_hosts:
      - "host.docker.internal:host-gateway"
